M48
; DRILL file {KiCad (6.0.1)} date Sun Feb 26 19:23:06 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-26T19:23:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.050
%
G90
G05
T1
X140.716Y-85.09
X140.716Y-118.618
T2
X181.208Y-86.104
X181.208Y-117.604
T0
M30
